### ISSUE TITLE
Better label for user e-mail

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/gui#149]
In user detail sidebar, the e-mail label is set to "Confirm email". This seems strange, as a simple "E-mail" label would be better.

![captura de tela em 2018-04-17 15-56-34](https://user-images.githubusercontent.com/6285982/38890564-2966d20a-4258-11e8-883f-550c357fbd16.png)

**Comment by mmagr** [comment]
mmm, I think we might be lost in requirements here.

I think there should be two slightly different versions of the form:

**1. User creation**
When creating a user, it seems reasonable to ask him/her to type in the email twice, as it works as some sort of weak typo detection feature (remember that email is important, otherwise the user will be locked out of the system).
On the other hand, this variation of the form *must not* have a password field - as it will be created using the "password recovery" mechanism.
While it's not my intention to hijack the issue, here we *should* also present the `tenant` field.

**2. User reading (user checking out its own info)**
When viewing itself, the confirmation field does seem out of place, so perhaps it could be removed (notice that we do already have an `email` field).
A password field *should* also be present, allowing the user to update its password.

**3. User reading (user checking some other user's info)**
Same as **2**, with the exception being that password field *must not* be editable (or visible for that matter).

**4. User update**
Here, we might want to keep both email fields - the same weak typo detection best practice *might* still apply.

**Comment by giovannicuriel** [comment]
Got it. As this is almost 1 year old :tada:, let's keep the way it is :smile:
